replicaCount: 1

redis:
  enabled: false
  persistence:
    enabled: false
  replica:
    replicaCount: 0
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

httpRoute:
  enabled: false
  gatewayNamespace: istio-ingress
  parentRefs: []
  hostnames: []
  matches: []
  filters: [ ]
  backendRefs: [ ]

deployment:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: latest

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2

  livenessProbe: {}

  readinessProbe: {}

  volumes: [ ]
  volumeMounts: [ ]
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  env: [ ]
  imagePullSecrets: [ ]
  annotations: { }
  labels: { }

externalSecrets:
  credentialsRef:
    secretName: universal-auth-credentials
    secretNamespace: infisical
  secretsScope:
    projectSlug: development-ko-nv
    envSlug: dev
    secretsPath: "/"
    recursive: true

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
