nameOverride: ""
fullnameOverride: ""

httpRoute:
  enabled: true
  parentRefs:
    - name: "api-gateway"
      sectionName: "wildcard-tls"
      namespace: "consul"
  hostnames: []
  path:
    type: PathPrefix
    value: /

service:
  type: ClusterIP
  protocol: TCP
  port: 8080
  annotations: {}
  labels: {}

serviceAccount:
  automount: true
  annotations: {}
  name: ""

deployment:
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/transparent-proxy: 'true'

  labels: {}

  image:
    repository: docker.io/datawire/quote
    pullPolicy: IfNotPresent
    tag: "0.5.0"
    imagePullSecrets: { }
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP

  volumes: [ ]
  volumeMounts: [ ]
  securityContext: { }
  tolerations: [ ]
  env: { }

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi

  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10



