nameOverride: ""
fullnameOverride: ""

httpRoute:
  enabled: true
  subdomain: "auth"
  environment: "development"
  domain: "tradecrit.com"
  referenceGrants: []
  parentRefs:
    - name: "api-gateway"
      sectionName: "tls"
      namespace: "istio-gateway"
  pathPrefix: "/"
  replacePrefixMatch: "/"

service:
  type: ClusterIP
  protocol: TCP
  port: 8080
  annotations: {}
  labels: {}

serviceAccount:
  automount: true
  annotations: {}
  name: ""

deployment:
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
#    vault.hashicorp.com/role: 'web'
#    vault.hashicorp.com/agent-inject-secret-config: 'secret/data/web'
#    vault.hashicorp.com/agent-inject-template-config: |
#      {{- with secret "secret/data/web" -}}
#        export api_key="{{ .Data.data.payments_api_key }}"
#      {{- end }}

  labels: {}

  image:
    repository: ""
    pullPolicy: Always
    tag: "latest"
    imagePullSecrets:
      - name: dockerconfigjson-sync

  args: [ ]
  command: [ ]

  volumes: [ ]
  volumeMounts: [ ]
  securityContext: { }
  tolerations: [ ]

  env: { }

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  resources:
    limits:
        cpu: 250m
        memory: 256Mi
    requests:
        cpu: 100m
        memory: 128Mi

  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
