apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes

type: application
version: 0.1.2
appVersion: "1.16.0"

dependencies:
  - name: grafana
    condition: grafana.enabled
    version: 8.10.*
    repository: https://grafana.github.io/helm-charts
  - name: loki
    condition: loki.enabled
    version: 6.27.*
    repository: https://grafana.github.io/helm-charts
#  - name: tempo-distributed
#    alias: tempo
#    condition: tempo.enabled
#    repository: "https://grafana.github.io/helm-charts"
#    version: 1.32.*
  - name: alloy
    condition: alloy.enabled
    version: 0.12.*
    repository: https://grafana.github.io/helm-charts
  - name: kube-prometheus-stack
    version: 69.5.*
    repository: https://prometheus-community.github.io/helm-charts
