apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: grafana
    condition: grafana.enabled
    version: 8.9.0
    repository: https://grafana.github.io/helm-charts
  - name: loki
    alias: loki
    condition: loki.enabled
    version: 6.26.0
    repository: https://grafana.github.io/helm-charts
  - name: mimir-distributed
    alias: mimir
    condition: mimir.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^5.6.0"
  - name: tempo-distributed
    alias: tempo
    condition: tempo.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: 1.32.0
