apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: grafana
    condition: grafana.enabled
    version: 8.9.0
    repository: https://grafana.github.io/helm-charts
  - name: loki
    condition: loki.enabled
    version: 6.26.0
    repository: https://grafana.github.io/helm-charts
  - name: prometheus
    condition: prometheus.enabled
    version: 27.3.0
    repository: https://prometheus-community.github.io/helm-charts
