mimir:
  enabled: false
  minio:
    enabled: false
  alertmanager:
    resources:
      requests:
        cpu: 20m
  compactor:
    resources:
      requests:
        cpu: 20m
  distributor:
    resources:
      requests:
        cpu: 20m
  ingester:
    replicas: 1
    zoneAwareReplication:
      enabled: false
    resources:
      requests:
        cpu: 20m
  overrides_exporter:
    resources:
      requests:
        cpu: 20m
  querier:
    replicas: 1
    resources:
      requests:
        cpu: 20m
  query_frontend:
    resources:
      requests:
        cpu: 20m
  query_scheduler:
    replicas: 1
    resources:
      requests:
        cpu: 20m
  ruler:
    resources:
      requests:
        cpu: 20m
  store_gateway:
    zoneAwareReplication:
      enabled: false
    resources:
      requests:
        cpu: 20m
  rollout_operator:
    resources:
      requests:
        cpu: 20m


tempo:
  enabled: false
  minio:
    enabled: false
  ingester:
    replicas: 1
    resources:
      requests:
        cpu: 20m
  storage:
    trace:
      backend: s3
      s3:
        endpoint: minio.minio-tenant.svc.cluster.local
        secretAccessKey: ""
        accessKeyId: storage-user
        bucket: 'tempo-traces'
        signatureVersion: v4
        s3ForcePathStyle: true
        insecure: false
        http_config:
          insecure_skip_verify: true  # Skip TLS certificate verification
  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
    zipkin:
      enabled: false
    jaeger:
      thriftHttp:
        enabled: false
    opencensus:
      enabled: false
