apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "job.fullname" . }}-dockerconfigjson
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.externalSecrets.credentialsRef.secretName }}
        secretNamespace: {{ .Values.externalSecrets.credentialsRef.secretNamespace }}
      secretsScope:
        projectSlug: development-ko-nv
        envSlug: {{ .Values.externalSecrets.secretsScope.envSlug }}
        secretsPath: "/github"
        recursive: false
  managedSecretReference:
    secretName: {{ include "job.fullname" . }}-dockerconfigjson
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: "Owner" ## Owner | Orphan
    secretType: kubernetes.io/dockerconfigjson
