apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "job.fullname" . }}
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: {{ .Values.externalSecrets.resyncInterval | default 10 }}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.externalSecrets.credentialsRef.secretName }}
        secretNamespace: {{ .Values.externalSecrets.credentialsRef.secretNamespace | default .Release.Namespace }}
      secretsScope:
        projectSlug: {{ .Values.externalSecrets.secretsScope.projectSlug | default "development-ko-nv"}}
        envSlug: {{ .Values.externalSecrets.secretsScope.envSlug | default "dev"}}
        secretsPath: {{ .Values.externalSecrets.secretsScope.secretsPath }}
        recursive: {{ .Values.externalSecrets.secretsScope.recursive | default true }}
  managedSecretReference:
    secretName: {{ include "job.fullname" . }}
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: "Owner" ## Owner | Orphan
    secretType: Opaque
