apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "job.fullname" . }}-cronjob
  labels:
    {{- include "job.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: {{ .Values.jobHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.jobHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          annotations:
            # disable istio on the pod due to this issue:
            # https://github.com/istio/istio/issues/11659
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: {{ include "job.serviceAccountName" . }}
          imagePullSecrets:
            - name: {{ include "job.fullname" . }}-dockerconfigjson
          containers:
            - name: {{ .Chart.Name }}-cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- range .Values.env }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}
              {{- if .Values.externalSecrets.enabled }}
              envFrom:
                - secretRef:
                    name: {{ .Values.externalSecrets.managedSecretReference.secretName }}
              {{ end }}
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
              {{- toYaml . | nindent 12 }}
          {{- end }}
