apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "job.fullname" . }}-cronjob
  labels:
    {{- include "job.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "job.labels" . | nindent 8 }}
        spec:
          serviceAccountName: {{ include "job.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}-cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- range .Values.args }}
                - {{ . | quote }}
                {{- end }}
              env:
                {{- toYaml .Values.deployment.env | nindent 12 }}
              {{ if .Values.externalSecrets.enabled}}
              envFrom:
                - secretRef:
                    name: {{ .Values.externalSecrets.managedSecretReference.secretName }}
              {{ end }}
          restartPolicy: OnFailure
