nameOverride: ""
fullnameOverride: ""

replicaCount: 1

environment_slug: dev
environment: development

httpRoute:
  enabled: false
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: api-gateway
  subdomain: myapp
  environment: development
  domain: example.com
  pathPrefix: /
  replacePrefixMatch: /

deployment:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: latest

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
      httpHeaders: []
    initialDelaySeconds: 3
    periodSeconds: 3

  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
      httpHeaders: []
    initialDelaySeconds: 3
    periodSeconds: 3

  volumes: [ ]
  volumeMounts: [ ]
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  env: [ ]
  imagePullSecrets: [ ]
  annotations: { }
  labels: { }

externalSecrets:
  enabled: false
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: development
        envSlug: dev
        secretsPath: "/"
        recursive: true
      credentialsRef:
          secretName: universal-auth-credentials
          secretNamespace: infisical
  managedSecretReference:
    secretName: secret
    secretType: Opaque

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
