---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: dockerconfigjson
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: development-ko-nv
        envSlug: dev
        secretsPath: "/DOCKERCONFIGJSON"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    secretName: dockerconfigjson
    secretNamespace: dynamic-dns
    creationPolicy: "Owner"
    secretType: kubernetes.io/dockerconfigjson