{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "service.fullname" . }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    - "{{ .Values.httpRoute.subdomain }}.{{ .Values.httpRoute.environment }}.{{ .Values.httpRoute.domain }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httpRoute.pathPrefix | quote}}
      backendRefs:
        - name: {{ include "service.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 100
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: {{ .Values.httpRoute.replacePrefixMatch | quote}}
{{- end -}}
