apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |
    // ADDITIONAL SERVICE CONFIGURATION
    prometheus.scrape "grafana" {
      targets = [
        {
          "__address__" = "grafana:8080",
          "application" = "grafana",
        },
      ]
      scrape_interval = "15s"
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    // Meta monitoring of alloy
    prometheus.exporter.self "default" {
    }

    prometheus.scrape "metamonitoring" {
      targets    = prometheus.exporter.self.default.targets
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    logging {
      level    = "info"
      format   = "json"
      write_to = [loki.write.default.receiver]
    }

    tracing {
      sampling_fraction = 0.1
      write_to          = [otelcol.exporter.otlp.default.input]
    }

    // Enable collection of metrics from the Prometheus Operator service monitors
    prometheus.operator.servicemonitors "servicemonitors" {
        forward_to = [prometheus.remote_write.mimir.receiver]
    }
    prometheus.operator.podmonitors "podmonitors" {
      forward_to = [prometheus.remote_write.mimir.receiver]
    }
    prometheus.operator.probes "probes" {
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    // Kubernetes discovery
    discovery.kubernetes "k8s_pods" {
      role = "pod"
    }

    prometheus.scrape "k8s_pods" {
      targets    = discovery.kubernetes.k8s_pods.targets
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    discovery.kubernetes "k8s_nodes" {
      role = "node"
    }

    prometheus.scrape "k8s_nodes" {
      targets    = discovery.kubernetes.k8s_nodes.targets
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    // COLLECT CONFIGURATION
    otelcol.receiver.otlp "default" {
        grpc { }
        http { }
        output {
            metrics = [otelcol.processor.resourcedetection.default.input]
            logs    = [otelcol.processor.resourcedetection.default.input]
            traces  = [otelcol.processor.resourcedetection.default.input]
        }
    }

    otelcol.processor.resourcedetection "default" {
        detectors = ["env", "system"]

        system {
            hostname_sources = ["os"]
        }

        output {
            metrics = [otelcol.processor.transform.drop_unneeded_resource_attributes.input]
            logs    = [otelcol.processor.transform.drop_unneeded_resource_attributes.input]
            traces  = [otelcol.processor.transform.drop_unneeded_resource_attributes.input]
        }
    }

    otelcol.processor.transform "drop_unneeded_resource_attributes" {
        // https://grafana.com/docs/alloy/latest/reference/components/otelcol.processor.transform/
        error_mode = "ignore"

        trace_statements {
            context    = "resource"
            statements = [
                "delete_key(attributes, \"k8s.pod.start_time\")",
                "delete_key(attributes, \"os.description\")",
                "delete_key(attributes, \"os.type\")",
                "delete_key(attributes, \"process.command_args\")",
                "delete_key(attributes, \"process.executable.path\")",
                "delete_key(attributes, \"process.pid\")",
                "delete_key(attributes, \"process.runtime.description\")",
                "delete_key(attributes, \"process.runtime.name\")",
                "delete_key(attributes, \"process.runtime.version\")",
            ]
        }

        metric_statements {
            context    = "resource"
            statements = [
                "delete_key(attributes, \"k8s.pod.start_time\")",
                "delete_key(attributes, \"os.description\")",
                "delete_key(attributes, \"os.type\")",
                "delete_key(attributes, \"process.command_args\")",
                "delete_key(attributes, \"process.executable.path\")",
                "delete_key(attributes, \"process.pid\")",
                "delete_key(attributes, \"process.runtime.description\")",
                "delete_key(attributes, \"process.runtime.name\")",
                "delete_key(attributes, \"process.runtime.version\")",
            ]
        }

        log_statements {
            context    = "resource"
            statements = [
                "delete_key(attributes, \"k8s.pod.start_time\")",
                "delete_key(attributes, \"os.description\")",
                "delete_key(attributes, \"os.type\")",
                "delete_key(attributes, \"process.command_args\")",
                "delete_key(attributes, \"process.executable.path\")",
                "delete_key(attributes, \"process.pid\")",
                "delete_key(attributes, \"process.runtime.description\")",
                "delete_key(attributes, \"process.runtime.name\")",
                "delete_key(attributes, \"process.runtime.version\")",
            ]
        }

        output {
            metrics = [otelcol.processor.transform.add_resource_attributes_as_metric_attributes.input]
            logs    = [otelcol.processor.batch.default.input]
            traces  = [
                otelcol.processor.batch.default.input,
                otelcol.connector.host_info.default.input,
            ]
        }
    }

    otelcol.connector.host_info "default" {
        host_identifiers = ["host.name"]

        output {
            metrics = [otelcol.processor.batch.default.input]
        }
    }

    otelcol.processor.transform "add_resource_attributes_as_metric_attributes" {
        error_mode = "ignore"

        metric_statements {
        context    = "datapoint"
        statements = [
            "set(attributes[\"deployment.environment\"], resource.attributes[\"deployment.environment\"])",
            "set(attributes[\"service.version\"], resource.attributes[\"service.version\"])",
            ]
        }

        output {
            metrics = [otelcol.processor.batch.default.input]
        }
    }

    otelcol.processor.batch "default" {
      output {
          metrics = [otelcol.exporter.prometheus.default.input]
          logs    = [otelcol.exporter.loki.default.input]
          traces  = [otelcol.exporter.otlp.default.input]
        }
    }

    otelcol.exporter.prometheus "default" {
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://grafana-mimir-nginx.monitoring.svc:80/api/v1/push"
      }
    }

    otelcol.exporter.loki "default" {
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://grafana-loki.monitoring.svc:3100/loki/api/v1/push"
      }
    }

    otelcol.exporter.otlp "default" {
        client {
            endpoint = "grafana-tempo.monitoring.svc:4317"
            tls {
                insecure = true
            }
        }
    }
