apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.write.local.receiver]
    }

    loki.source.kubernetes "nodes" {
      targets    = discovery.kubernetes.nodes.targets
      forward_to = [loki.write.local.receiver]
    }

    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "nodes" {
      role = "node"
    }
    discovery.kubernetes "services" {
      role = "service"
    }
    discovery.kubernetes "endpoints" {
      role = "endpoints"
    }
    discovery.kubernetes "endpointslices" {
      role = "endpointslice"
    }
    discovery.kubernetes "ingresses" {
      role = "ingress"
    }
    prometheus.scrape "grafana" {
      targets = [
        {"__address__" = "grafana.monitoring.svc:8080"},
      ]
      scrape_interval = "15s"
      forward_to = [prometheus.remote_write.default.receiver]
    }
    prometheus.remote_write "default" {
      endpoint {
        url = "http://grafana-mimir-nginx:80/api/v1/push"
      }
    }
