{{- if .Values.grafana.enabled -}}
{{- if .Values.grafana.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "monitoring.fullname" . }}
spec:
  {{- if .Values.grafana.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.grafana.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  parentRefs:
    {{- toYaml .Values.grafana.httpRoute.parentRefs | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /metrics
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /
            statusCode: 302
    - matches:
        {{- toYaml .Values.grafana.httpRoute.matches | nindent 8 }}
      backendRefs:
      {{- if .Values.grafana.httpRoute.backendRefs }}
        {{- toYaml .Values.grafana.httpRoute.backendRefs | nindent 8 }}
      {{- else }}
        - name: {{ include "monitoring.fullname" . }}
          namespace: {{ .Release.Namespace }}
          kind: Service
          port: {{ .Values.grafana.service.port }}
      {{- end }}
      {{- if .Values.grafana.httpRoute.filters }}
      filters:
        {{- toYaml .Values.grafana.httpRoute.filters | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- end }}
