- apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalSecret
  metadata:
    name: storage-user
    namespace: monitoring
  spec:
    hostAPI: https://app.infisical.com/api
    resyncInterval: 10
    authentication:
      universalAuth:
        secretsScope:
          projectSlug: development-ko-nv
          envSlug: dev
          secretsPath: "/minio-storage-user"
          recursive: true
        credentialsRef:
          secretName: universal-auth-credentials
          secretNamespace: infisical
    managedSecretReference:
      secretName: storage-user
      secretNamespace: minio-tenant
      creationPolicy: "Owner" ## Owner | Orphan
---
- apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalSecret
  metadata:
    name: storage-configuration
    namespace: monitoring
  spec:
    hostAPI: https://app.infisical.com/api
    resyncInterval: 10
    authentication:
      universalAuth:
        secretsScope:
          projectSlug: development-ko-nv
          envSlug: dev
          secretsPath: "/minio-config"
          recursive: true
        credentialsRef:
          secretName: universal-auth-credentials
          secretNamespace: infisical
    managedSecretReference:
      secretName: storage-configuration
      secretNamespace: minio-tenant
      creationPolicy: "Owner" ## Owner | Orphan
