---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ include "tradecrit-external-secrets.fullname" . }}-dockerconfigjson
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "dockerconfigjson-sync"

  namespaceSelector:
    matchLabels:
      private-registry-access: "enabled"

  refreshTime: "15s"

  externalSecretSpec:
    refreshInterval: "15s"
    secretStoreRef:
      name: {{ include "tradecrit-external-secrets.fullname" . }}
      kind: ClusterSecretStore

    target:
      name: dockerconfigjson-sync
      creationPolicy: "Owner"
      template:
        type: kubernetes.io/dockerconfigjson
        metadata:
          annotations: {}
          labels: {}

    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: dockerconfigjson
          property: "config"
