{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "vault-token" -}}
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
type: Opaque
data:
  {{- if $existingSecret }}
  token: {{ index $existingSecret.data "token" }}
  {{- else }}
  token: {{ .Values.backend.vault.token | b64enc }}
  {{- end }}