schedule: "0 0 * * *"

jobHistoryLimit: 3

args: [ ]

image:
  repository: ""
  pullPolicy: "Always"
  tag: ""

env: [ ]

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumes: [ ]

volumeMounts: [ ]

nodeSelector: { }

externalSecrets:
  enabled: false
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: development
        envSlug: dev
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    secretName: secret
    secretType: Opaque
