apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "microservice.fullname" . }}-dockerconfigjson
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: {{ .Values.externalSecrets.identityId }}
      serviceAccountRef:
        name: infisical-auth
        namespace: infisical
      secretsScope:
        projectSlug: development-ko-nv
        envSlug: {{ .Values.externalSecrets.secretsScope.envSlug }}
        secretsPath: "/github"
        recursive: false
  managedSecretReference:
    secretName: {{ include "microservice.fullname" . }}-dockerconfigjson
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: "Owner" ## Owner | Orphan
    secretType: kubernetes.io/dockerconfigjson
