apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Release.Name }}-microservice
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: {{ .Values.externalSecrets.resyncInterval | default 10 }}
  authentication:
    kubernetesAuth:
      identityId: f4f297f4-f8ee-4d21-9d4c-c9bac0e21aaf
      serviceAccountRef:
        name: infisical-auth
        namespace: infisical
      secretsScope:
        projectSlug: {{ .Values.externalSecrets.secretsScope.projectSlug | default "development-ko-nv"}}
        envSlug: {{ .Values.externalSecrets.secretsScope.envSlug | default "dev"}}
        secretsPath: {{ .Values.externalSecrets.secretsScope.secretsPath }}
        recursive: {{ .Values.externalSecrets.secretsScope.recursive | default true }}
  managedSecretReference:
    secretName: {{ .Release.Name }}-microservice
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: "Owner" ## Owner | Orphan
    secretType: Opaque
