{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "microservice.fullname" . }}
spec:
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  rules:
    - matches:
        {{- toYaml .Values.httpRoute.matches | nindent 8 }}
      backendRefs:
      {{- if .Values.httpRoute.backendRefs }}
        {{- toYaml .Values.httpRoute.backendRefs | nindent 8 }}
      {{- else }}
        - name: {{ include "microservice.fullname" . }}
          namespace: {{ .Release.Namespace }}
          kind: Service
          port: {{ .Values.service.port }}
      {{- end }}
      {{- if .Values.httpRoute.filters }}
      filters:
        {{- toYaml .Values.httpRoute.filters | nindent 8 }}
      {{- end }}
{{- end -}}
