{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "microservice.fullname" . }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  rules:
    - matches:
        {{- toYaml .Values.httpRoute.matches | nindent 8 }}
      backendRefs:
        - name: {{ include "microservice.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 1
      filters:
        {{- toYaml .Values.httpRoute.filters | nindent 8 }}
{{- end -}}
