---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name:  {{ include "webserver.fullname" . }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: istio-gateway
  to:
    - group: ""
      kind: Service
      name: {{ include "webserver.fullname" .}}
