---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name:  {{ include "webserver.fullname" . }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: istio-gateway
  to:
    {{- range .Values.httpRoute.referenceGrants }}
    - group: ""
      kind: Service
      name: {{ . | quote}}
    {{- end }}
