apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "webserver.fullname" . }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: {{ .Values.httpRoute.path.type }}
            value: {{ .Values.httpRoute.path.value }}
      backendRefs:
        - name:  {{ include "webserver.fullname" . }}
          port: {{ .Values.service.port }}