{{- if .Values.httpRoute.enabled -}}
{{- $parentRefs := .Values.httpRoute.parentRefs }}
{{- $hostnames := .Values.httpRoute.hostnames }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "webserver.fullname" . }}
spec:
  parentRefs:
    {{- toYaml $parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml $hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: {{ .Values.httpRoute.path.type }}
            value: {{ .Values.httpRoute.path.value }}
      backendRefs:
        - name:  {{ include "webserver.fullname" . }}
          port: {{ .Values.service.port }}
{{- end -}}
