{{- if .Values.httpRoute.enabled -}}
{{- $parentRefs := .Values.httpRoute.parentRefs }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "webserver.fullname" . }}
spec:
  parentRefs:
    {{- toYaml $parentRefs | nindent 4 }}
  hostnames:
    - "{{ .Values.httpRoute.subdomain }}.{{ .Values.httpRoute.environment }}.tradecrit.com"
  rules:
    - matches:
        - path:
            type: {{ .Values.httpRoute.path.type }}
            value: {{ .Values.httpRoute.path.value }}
      filters:
        {{ if .Values.httpRoute.filters }}
        {{- toYaml .Values.httpRoute.filters | nindent 8 }}
        {{- end }}
      backendRefs:
        - name:  {{ include "webserver.fullname" . }}
          port: {{ .Values.service.port }}
{{- end -}}
